import numpy as np
import torch
from monai.transforms import MapTransform
from monai.config import KeysCollection
from typing import Mapping, Hashable, Dict

class LoadNpyD(MapTransform):
    """
    Custom Transform to load .npy files generated by the preprocessing script.
    The preprocessing script saved them as (C, D, H, W) or (1, D, H, W).
    """
    def __init__(self, keys: KeysCollection, allow_missing_keys: bool = False):
        super().__init__(keys, allow_missing_keys)

    def __call__(self, data: Mapping[Hashable, str]) -> Dict[Hashable, np.ndarray]:
        d = dict(data)
        for key in self.key_iterator(d):
            try:
                # Load .npy
                # Preprocessing output: np.save(..., np.expand_dims(img, 0))
                # Shape is likely (1, D, H, W)
                arr = np.load(d[key])
                
                # Ensure it is float32 for image, but keep original for label initially
                if key == "image":
                    arr = arr.astype(np.float32)
                
                d[key] = arr
                
                # Metadata mock to satisfy some MONAI transforms if needed
                if "image_meta_dict" not in d:
                    d["image_meta_dict"] = {"filename_or_obj": d[key]}
            except Exception as e:
                raise RuntimeError(f"Failed to load {d[key]}: {e}")
        return d